name: Deploy Websites to AWS S3

on:
  push:
    branches:
      - main
    paths:
      - 'AWS_Handy_Book/**'
      - 'AWS_CloudShell_Commands/**'
      - '.github/workflows/deploy-to-s3.yml'

jobs:
  deploy:
    name: Sync to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy AWS Handy Book to S3
        run: |
          aws s3 sync AWS_Handy_Book/website/ s3://${{ secrets.HANDY_BOOK_S3_BUCKET }} --delete --exclude ".git/*"

      - name: Deploy CloudShell Commands to S3
        run: |
          aws s3 sync AWS_CloudShell_Commands/ s3://${{ secrets.CLOUDSHELL_S3_BUCKET }} --delete --exclude ".git/*"

      # Optional: Invalidate CloudFront Distribution if you use one
      # - name: Invalidate CloudFront
      #   run: |
      #     aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths "/*"
# trigger workflow
